// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ParserDbContext;

#nullable disable

namespace ParserDbContext.Migrations
{
    [DbContext(typeof(ParserContext))]
    [Migration("20231127062026_Product_Name_Update")]
    partial class Product_Name_Update
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.14");

            modelBuilder.Entity("ParserDbContext.Entities.Product", b =>
                {
                    b.Property<uint>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double?>("LastFetchedPrice")
                        .HasColumnType("REAL");

                    b.Property<uint>("NameId")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("ShopId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ProductId");

                    b.HasIndex("NameId");

                    b.HasIndex("ShopId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("ParserDbContext.Entities.ProductsNames", b =>
                {
                    b.Property<uint>("ProductsNamesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ProductsNamesId");

                    b.ToTable("ProductsNames");
                });

            modelBuilder.Entity("ParserDbContext.Entities.Shop", b =>
                {
                    b.Property<uint>("ShopId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ShopId");

                    b.ToTable("Shops");
                });

            modelBuilder.Entity("ParserDbContext.Entities.Product", b =>
                {
                    b.HasOne("ParserDbContext.Entities.ProductsNames", "Name")
                        .WithMany()
                        .HasForeignKey("NameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ParserDbContext.Entities.Shop", "Shop")
                        .WithMany()
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Name");

                    b.Navigation("Shop");
                });
#pragma warning restore 612, 618
        }
    }
}
